.PHONY: clean All

All:
	@echo "----------Building project:[ rrg_fixed_size - Debug ]----------"
	@cd "rrg_fixed_size" && "$(MAKE)" -f  "rrg_fixed_size.mk"
clean:
	@echo "----------Cleaning project:[ rrg_fixed_size - Debug ]----------"
	@cd "rrg_fixed_size" && "$(MAKE)" -f  "rrg_fixed_size.mk" clean
